### ISSUE TITLE
hide title bar

### ISSUE THREAD

**Issue by MatthieuLamp** [miyako/4d-plugin-window-style#2]
Hi,

is it possible to have a command to hide title bar ?
Thanks.

**Comment by miyako** [comment]
I don't understand. the purpose of making the title bar transparent is to unify with the window content.

why would you want to hide it? you will lose the close, maximise, minimise buttons.

if you don't like the title bar why not use a different window type?

**Comment by MatthieuLamp** [comment]
<img width="1194" alt="Capture d’écran 2021-07-15 à 14 43 12" src="https://user-images.githubusercontent.com/48675663/125790128-04a0f6b8-10db-4ca9-bccb-22a3c9f5c05d.png">
<img width="1346" alt="Capture d’écran 2021-07-15 à 14 43 49" src="https://user-images.githubusercontent.com/48675663/125790134-5034be68-9527-4991-b604-72fc358929b2.png">
before after
I want to keep the closing buttons
but now I am losing this space because of the height of the title bar
and the background color is not a solution unfortunately
i hope i am understandable

**Comment by miyako** [comment]
I think it might be impossible. 

4D v19 needs to manage the background and title bar to support dark mode.

**Comment by MatthieuLamp** [comment]
never mind -(
thank you

**Comment by miyako** [comment]
I presume "background colour is not a solution" because the design is not a solid fill. how about a background image?

**Comment by miyako** [comment]
I tried [NSWindowTitleHidden](https://developer.apple.com/documentation/appkit/nswindowtitlevisibility/nswindowtitlehidden) but in v19 it only has the effect of removing the window title, the bar itself is not hidden.

perhaps it is necessary to change the window style as well.

**Comment by miyako** [comment]
I confirm that setting the window style to not have a title bar instantly crashes 4D.

**Comment by MatthieuLamp** [comment]
> I tried [NSWindowTitleHidden](https://developer.apple.com/documentation/appkit/nswindowtitlevisibility/nswindowtitlehidden) but in v19 it only has the effect of removing the window title, the bar itself is not hidden.
> 
> perhaps it is necessary to change the window style as well.

the result is the same as with 4d-plugin-apple-window-title-bar ?
