### ISSUE TITLE
move window

### ISSUE THREAD

**Issue by MatthieuLamp** [miyako/4d-plugin-window-style#3]
Hi,
if I apply this command, the whole window moves
and no longer just the title bar 
drag & drop result becomes inactive

Thanks

**Comment by miyako** [comment]
sounds like you set the [opaque](https://developer.apple.com/documentation/appkit/nswindow/1419086-opaque) option.

**Comment by MatthieuLamp** [comment]
It doesn't change anything

$style:=Créer objet
$style.opaque:=Faux  //https://developer.apple.com/documentation/appkit/nswindow/1419086-opaque?language=objc
$style.titlebarAppearsTransparent:=Vrai  //https://developer.apple.com/documentation/appkit/nswindow/1419167-titlebarappearstransparent?language=objc
$style.movableByWindowBackground:=Vrai  //https://developer.apple.com/documentation/appkit/nswindow/1419072-movablebywindowbackground?language=objc
$style.backgroundColor:=Créer objet
Si (Apparence_Lire="light")  // MODE CLAIR
	$style.backgroundColor.red:=1  // Blanc
	$style.backgroundColor.green:=1
	$style.backgroundColor.blue:=1
Sinon 
	$style.backgroundColor.red:=0,115  // Noir
	$style.backgroundColor.green:=0,115
	$style.backgroundColor.blue:=0,115
Fin de si 
$style.backgroundColor.alpha:=1  //

SET WINDOW STYLE(Fenêtre formulaire courant; $style)

**Comment by miyako** [comment]
what about `movableByWindowBackground` ?

**Comment by MatthieuLamp** [comment]
it's ok ;-)
thanks
